import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { Providers } from "./providers";
export const metadata = {
  title: "tasvirai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <Providers>
     <html lang="en">
      
      <body
      className={`${inter.className}  h-[100vh]`}
        
      >
        {children}
      </body>
      
    </html>
   </Providers>
  );
}
